# Write your query or mutation here
query posts {
  posts {
    data {
      attributes {
        titreInfo
        titreArticle
        description
        section {
          section
        }
        img {
          img1 {
            data {
              attributes {
                name
                url
              }
            }
          }
          img2 {
            data {
              attributes {
                name
                url
              }
            }
          }
        }
      }
    }
  }
}
