query posts {
  posts {
    data {
      id
      attributes {
        createdAt
        titreInfo
        description
        imgDescription {
          data {
            attributes {
              alternativeText
              url
            }
          }
        }
        titreArticle
        headerImg {
          img1 {
            data {
              attributes {
                alternativeText
                url
              }
            }
          }
        }
        section {
          titreSection
          section
          imgSection {
            data {
              attributes {
                alternativeText
                url
              }
            }
          }
        }
      }
    }
  }
}
# Write your query or mutation here
